// AUTO-GENERATED by tools/generate-catalog.js — do not edit by hand.
// Regenerate with: node tools/generate-catalog.js
window.CATALOG = [
  {
    "id": "bottles",
    "name": "Bottles",
    "image": "images/Bottles/Fridge Bottles/Classic/Main.jpg",
    "subcategories": [
      {
        "id": "fridge-bottles",
        "name": "Fridge Bottles",
        "image": "images/Bottles/Fridge Bottles/Classic/Main.jpg",
        "products": [
          {
            "id": "classic",
            "name": "Classic",
            "image": "images/Bottles/Fridge Bottles/Classic/Main.jpg",
            "images": [
              "images/Bottles/Fridge Bottles/Classic/Main.jpg",
              "images/Bottles/Fridge Bottles/Classic/Classic-1.jpg",
              "images/Bottles/Fridge Bottles/Classic/Classic-3.jpg",
              "images/Bottles/Fridge Bottles/Classic/Classic-4.jpg",
              "images/Bottles/Fridge Bottles/Classic/Classic-5.jpg",
              "images/Bottles/Fridge Bottles/Classic/Drinking Man.png",
              "images/Bottles/Fridge Bottles/Classic/HoldinhinHand.png",
              "images/Bottles/Fridge Bottles/Classic/OfficeBottle.png"
            ]
          },
          {
            "id": "curvy",
            "name": "Curvy",
            "image": "images/Bottles/Fridge Bottles/Curvy/Main.jpg",
            "images": [
              "images/Bottles/Fridge Bottles/Curvy/Main.jpg",
              "images/Bottles/Fridge Bottles/Curvy/Box.jpg",
              "images/Bottles/Fridge Bottles/Curvy/ChatGPT Image Dec 20, 2025, 10_29_24 PM.png",
              "images/Bottles/Fridge Bottles/Curvy/ChatGPT Image Dec 20, 2025, 10_33_55 PM.png",
              "images/Bottles/Fridge Bottles/Curvy/Curvy-1.jpg",
              "images/Bottles/Fridge Bottles/Curvy/Curvy-3.jpg",
              "images/Bottles/Fridge Bottles/Curvy/Curvy-4.jpg",
              "images/Bottles/Fridge Bottles/Curvy/Curvy-5.jpg",
              "images/Bottles/Fridge Bottles/Curvy/Screenshot 2025-12-22 224137.png"
            ]
          },
          {
            "id": "curvybsc",
            "name": "Curvy BSC",
            "image": "images/Bottles/Fridge Bottles/CurvyBSC/Main.jpeg",
            "images": [
              "images/Bottles/Fridge Bottles/CurvyBSC/Main.jpeg",
              "images/Bottles/Fridge Bottles/CurvyBSC/Dimension.jpg",
              "images/Bottles/Fridge Bottles/CurvyBSC/Features.jpg",
              "images/Bottles/Fridge Bottles/CurvyBSC/FeaturesFamily.jpg",
              "images/Bottles/Fridge Bottles/CurvyBSC/In hand curvy bottle.jpeg",
              "images/Bottles/Fridge Bottles/CurvyBSC/Office CurvyBottle.jpeg",
              "images/Bottles/Fridge Bottles/CurvyBSC/Open .jpg",
              "images/Bottles/Fridge Bottles/CurvyBSC/Package.png",
              "images/Bottles/Fridge Bottles/CurvyBSC/PackageImage.jpg"
            ]
          },
          {
            "id": "flora",
            "name": "Flora",
            "image": "images/Bottles/Fridge Bottles/FloraBlackLogo/Main.jpg",
            "images": [
              "images/Bottles/Fridge Bottles/FloraBlackLogo/Main.jpg",
              "images/Bottles/Fridge Bottles/FloraBlackLogo/Box.png",
              "images/Bottles/Fridge Bottles/FloraBlackLogo/Flora-1.jpg",
              "images/Bottles/Fridge Bottles/FloraBlackLogo/Flora-3.jpg",
              "images/Bottles/Fridge Bottles/FloraBlackLogo/Flora-4.jpg",
              "images/Bottles/Fridge Bottles/FloraBlackLogo/Flora-5.jpg",
              "images/Bottles/Fridge Bottles/FloraBlackLogo/Office.png"
            ]
          },
          {
            "id": "sports",
            "name": "Sports",
            "image": "images/Bottles/Fridge Bottles/Sports/Main.jpg",
            "images": [
              "images/Bottles/Fridge Bottles/Sports/Main.jpg",
              "images/Bottles/Fridge Bottles/Sports/ChatGPT Image Dec 20, 2025, 10_29_24 PM.png",
              "images/Bottles/Fridge Bottles/Sports/ChatGPT Image Dec 20, 2025, 10_33_55 PM.png",
              "images/Bottles/Fridge Bottles/Sports/Dec 20, 2025, 10_24_45 PM.png",
              "images/Bottles/Fridge Bottles/Sports/SportBottleBox.jpeg",
              "images/Bottles/Fridge Bottles/Sports/Sports-1.jpg",
              "images/Bottles/Fridge Bottles/Sports/Sports-3.jpg",
              "images/Bottles/Fridge Bottles/Sports/Sports-4.jpg",
              "images/Bottles/Fridge Bottles/Sports/Sports-5.jpg"
            ]
          }
        ]
      },
      {
        "id": "gym-bottles",
        "name": "Gym Bottles",
        "image": "images/Bottles/Gym Bottles/CurvyB/Main.png",
        "products": [
          {
            "id": "curvy-black",
            "name": "Curvy Black",
            "image": "images/Bottles/Gym Bottles/CurvyB/Main.png",
            "images": [
              "images/Bottles/Gym Bottles/CurvyB/Main.png",
              "images/Bottles/Gym Bottles/CurvyB/Curvy-4-Dimension.png",
              "images/Bottles/Gym Bottles/CurvyB/CV Bl GymGirl.png",
              "images/Bottles/Gym Bottles/CurvyB/CV Black Office.png",
              "images/Bottles/Gym Bottles/CurvyB/Man Holding.png",
              "images/Bottles/Gym Bottles/CurvyB/Package.png"
            ]
          },
          {
            "id": "sports-black-cap",
            "name": "Sports Black Cap",
            "image": "images/Bottles/Gym Bottles/SportsBlackCap/Main.png",
            "images": [
              "images/Bottles/Gym Bottles/SportsBlackCap/Main.png",
              "images/Bottles/Gym Bottles/SportsBlackCap/Gym.png",
              "images/Bottles/Gym Bottles/SportsBlackCap/Hometable.png",
              "images/Bottles/Gym Bottles/SportsBlackCap/InHand.png",
              "images/Bottles/Gym Bottles/SportsBlackCap/Office.png",
              "images/Bottles/Gym Bottles/SportsBlackCap/Package.png",
              "images/Bottles/Gym Bottles/SportsBlackCap/SportsBlackCapDimen.png"
            ]
          }
        ]
      },
      {
        "id": "hot-and-cold-bottles",
        "name": "Hot and Cold Bottles",
        "image": "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_30_33 PM.png",
        "products": [
          {
            "id": "climatepro-mattsteel",
            "name": "ClimatePro Matt Steel",
            "image": "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_30_33 PM.png",
            "images": [
              "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_30_33 PM.png",
              "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_43_49 PM.png",
              "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_49_33 PM.png",
              "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_50_52 PM.png",
              "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_59_11 PM.png",
              "images/Bottles/Hot and Cold Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 11_03_03 PM.png"
            ]
          },
          {
            "id": "climatepro-black",
            "name": "ClimatePro Black",
            "image": "images/Bottles/Hot and Cold Bottles/ClimatePro-Black.png",
            "images": [
              "images/Bottles/Hot and Cold Bottles/ClimatePro-Black.png"
            ]
          },
          {
            "id": "climatepro-crocodile",
            "name": "ClimatePro Crocodile",
            "image": "images/Bottles/Hot and Cold Bottles/ClimatePro-Crocodile.png",
            "images": [
              "images/Bottles/Hot and Cold Bottles/ClimatePro-Crocodile.png"
            ]
          },
          {
            "id": "dual-core-military-green",
            "name": "Dual Core Military Green",
            "image": "images/Bottles/Hot and Cold Bottles/Dual Core-Military Green.png",
            "images": [
              "images/Bottles/Hot and Cold Bottles/Dual Core-Military Green.png"
            ]
          },
          {
            "id": "dualcore-delta",
            "name": "Dual Core Delta",
            "image": "images/Bottles/Hot and Cold Bottles/DualCore-Delta.png",
            "images": [
              "images/Bottles/Hot and Cold Bottles/DualCore-Delta.png"
            ]
          },
          {
            "id": "dualcore-navyblue",
            "name": "Dual Core Navy Blue",
            "image": "images/Bottles/Hot and Cold Bottles/DualCOre-NavyBlue.png",
            "images": [
              "images/Bottles/Hot and Cold Bottles/DualCOre-NavyBlue.png"
            ]
          }
        ]
      },
      {
        "id": "sipper-bottles",
        "name": "Sipper Bottles",
        "image": "images/Bottles/Sipper Bottles/CurvyB/Main.png",
        "products": [
          {
            "id": "curvy-black",
            "name": "Curvy Black",
            "image": "images/Bottles/Sipper Bottles/CurvyB/Main.png",
            "images": [
              "images/Bottles/Sipper Bottles/CurvyB/Main.png",
              "images/Bottles/Sipper Bottles/CurvyB/Curvy-4-Dimension.png",
              "images/Bottles/Sipper Bottles/CurvyB/CV Bl GymGirl.png",
              "images/Bottles/Sipper Bottles/CurvyB/CV Black Office.png",
              "images/Bottles/Sipper Bottles/CurvyB/Man Holding.png",
              "images/Bottles/Sipper Bottles/CurvyB/Package.png"
            ]
          },
          {
            "id": "sports-black-cap",
            "name": "Sports Black Cap",
            "image": "images/Bottles/Sipper Bottles/SportsBlackCap/Main.png",
            "images": [
              "images/Bottles/Sipper Bottles/SportsBlackCap/Main.png",
              "images/Bottles/Sipper Bottles/SportsBlackCap/Gym.png",
              "images/Bottles/Sipper Bottles/SportsBlackCap/Hometable.png",
              "images/Bottles/Sipper Bottles/SportsBlackCap/InHand.png",
              "images/Bottles/Sipper Bottles/SportsBlackCap/Office.png",
              "images/Bottles/Sipper Bottles/SportsBlackCap/Package.png",
              "images/Bottles/Sipper Bottles/SportsBlackCap/SportsBlackCapDimen.png"
            ]
          }
        ]
      },
      {
        "id": "travel-bottles",
        "name": "Travel Bottles",
        "image": "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_30_33 PM.png",
        "products": [
          {
            "id": "climatepro-mattsteel",
            "name": "ClimatePro Matt Steel",
            "image": "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_30_33 PM.png",
            "images": [
              "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_30_33 PM.png",
              "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_43_49 PM.png",
              "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_49_33 PM.png",
              "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_50_52 PM.png",
              "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 10_59_11 PM.png",
              "images/Bottles/Travel Bottles/ClimatePro-MattSteel/ChatGPT Image Jul 1, 2026, 11_03_03 PM.png"
            ]
          },
          {
            "id": "curvy-black",
            "name": "Curvy Black",
            "image": "images/Bottles/Travel Bottles/CurvyB/Main.png",
            "images": [
              "images/Bottles/Travel Bottles/CurvyB/Main.png",
              "images/Bottles/Travel Bottles/CurvyB/Curvy-4-Dimension.png",
              "images/Bottles/Travel Bottles/CurvyB/CV Bl GymGirl.png",
              "images/Bottles/Travel Bottles/CurvyB/CV Black Office.png",
              "images/Bottles/Travel Bottles/CurvyB/Man Holding.png",
              "images/Bottles/Travel Bottles/CurvyB/Package.png"
            ]
          },
          {
            "id": "sports-black-cap",
            "name": "Sports Black Cap",
            "image": "images/Bottles/Travel Bottles/SportsBlackCap/Main.png",
            "images": [
              "images/Bottles/Travel Bottles/SportsBlackCap/Main.png",
              "images/Bottles/Travel Bottles/SportsBlackCap/Gym.png",
              "images/Bottles/Travel Bottles/SportsBlackCap/Hometable.png",
              "images/Bottles/Travel Bottles/SportsBlackCap/InHand.png",
              "images/Bottles/Travel Bottles/SportsBlackCap/Office.png",
              "images/Bottles/Travel Bottles/SportsBlackCap/Package.png",
              "images/Bottles/Travel Bottles/SportsBlackCap/SportsBlackCapDimen.png"
            ]
          },
          {
            "id": "climatepro-black",
            "name": "ClimatePro Black",
            "image": "images/Bottles/Travel Bottles/ClimatePro-Black.png",
            "images": [
              "images/Bottles/Travel Bottles/ClimatePro-Black.png"
            ]
          },
          {
            "id": "climatepro-crocodile",
            "name": "ClimatePro Crocodile",
            "image": "images/Bottles/Travel Bottles/ClimatePro-Crocodile.png",
            "images": [
              "images/Bottles/Travel Bottles/ClimatePro-Crocodile.png"
            ]
          },
          {
            "id": "dual-core-military-green",
            "name": "Dual Core Military Green",
            "image": "images/Bottles/Travel Bottles/Dual Core-Military Green.png",
            "images": [
              "images/Bottles/Travel Bottles/Dual Core-Military Green.png"
            ]
          },
          {
            "id": "dualcore-delta",
            "name": "Dual Core Delta",
            "image": "images/Bottles/Travel Bottles/DualCore-Delta.png",
            "images": [
              "images/Bottles/Travel Bottles/DualCore-Delta.png"
            ]
          },
          {
            "id": "dualcore-navyblue",
            "name": "Dual Core Navy Blue",
            "image": "images/Bottles/Travel Bottles/DualCOre-NavyBlue.png",
            "images": [
              "images/Bottles/Travel Bottles/DualCOre-NavyBlue.png"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "combo",
    "name": "Combo Sets",
    "image": "images/Combo/Combo-Classic.jpg",
    "subcategories": [
      {
        "id": "",
        "name": "",
        "image": "images/Combo/Combo-Classic.jpg",
        "products": [
          {
            "id": "combo-classic",
            "name": "Combo Classic",
            "image": "images/Combo/Combo-Classic.jpg",
            "images": [
              "images/Combo/Combo-Classic.jpg"
            ]
          },
          {
            "id": "combo-curvy",
            "name": "Combo Curvy",
            "image": "images/Combo/Combo-Curvy.jpg",
            "images": [
              "images/Combo/Combo-Curvy.jpg"
            ]
          },
          {
            "id": "combo-flora",
            "name": "Combo Flora",
            "image": "images/Combo/Combo-Flora.jpg",
            "images": [
              "images/Combo/Combo-Flora.jpg"
            ]
          },
          {
            "id": "combo-sports",
            "name": "Combo Sports",
            "image": "images/Combo/Combo-Sports.jpg",
            "images": [
              "images/Combo/Combo-Sports.jpg"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "dustbin",
    "name": "Dustbins",
    "image": "images/Dustbin/DustbinPerforated/Main.png",
    "subcategories": [
      {
        "id": "",
        "name": "",
        "image": "images/Dustbin/DustbinPerforated/Main.png",
        "products": [
          {
            "id": "perforated",
            "name": "Perforated",
            "image": "images/Dustbin/DustbinPerforated/Main.png",
            "images": [
              "images/Dustbin/DustbinPerforated/Main.png",
              "images/Dustbin/DustbinPerforated/Dustbin-Perforated-2 BL.png",
              "images/Dustbin/DustbinPerforated/Dustbin-Perforated-3-BL.png",
              "images/Dustbin/DustbinPerforated/Kitchen.png",
              "images/Dustbin/DustbinPerforated/Office.png",
              "images/Dustbin/DustbinPerforated/Room.png"
            ]
          },
          {
            "id": "perforated-pedal",
            "name": "Perforated Pedal",
            "image": "images/Dustbin/DustbinPerfWithPeddal/Main.png",
            "images": [
              "images/Dustbin/DustbinPerfWithPeddal/Main.png",
              "images/Dustbin/DustbinPerfWithPeddal/Dustbin-Perforated with lid-2.jpg",
              "images/Dustbin/DustbinPerfWithPeddal/Dustbin-Perforated with lid-3.jpg",
              "images/Dustbin/DustbinPerfWithPeddal/Dustbin-Perforated with lid-4.jpg",
              "images/Dustbin/DustbinPerfWithPeddal/Main1.jpg"
            ]
          },
          {
            "id": "smooth-pedal",
            "name": "Smooth Pedal",
            "image": "images/Dustbin/DustbinSmoothwithpeddal/Main.jpg",
            "images": [
              "images/Dustbin/DustbinSmoothwithpeddal/Main.jpg",
              "images/Dustbin/DustbinSmoothwithpeddal/Dustbin-Smooth finish- 2.jpg",
              "images/Dustbin/DustbinSmoothwithpeddal/Dustbin-Smooth finish- 3.jpg",
              "images/Dustbin/DustbinSmoothwithpeddal/Dustbin-Smooth finish- 4.jpg"
            ]
          },
          {
            "id": "swing",
            "name": "Swing Lid",
            "image": "images/Dustbin/Swing/Main.png",
            "images": [
              "images/Dustbin/Swing/Main.png"
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "lunchbox",
    "name": "Lunch Boxes",
    "image": "images/LunchBox/Tiffini30/Main.jpg",
    "subcategories": [
      {
        "id": "",
        "name": "",
        "image": "images/LunchBox/Tiffini30/Main.jpg",
        "products": [
          {
            "id": "tiffin-30",
            "name": "Tiffin 30",
            "image": "images/LunchBox/Tiffini30/Main.jpg",
            "images": [
              "images/LunchBox/Tiffini30/Main.jpg",
              "images/LunchBox/Tiffini30/Screenshot 2025-11-10 223157.jpg",
              "images/LunchBox/Tiffini30/Tiffin-2.jpg",
              "images/LunchBox/Tiffini30/Tiffin-3.jpg",
              "images/LunchBox/Tiffini30/Tiffin-4.jpg"
            ]
          },
          {
            "id": "tiffin-steel-lid-black",
            "name": "Tiffin Steel Lid Black",
            "image": "images/LunchBox/TiffinSteellidBlack/Main.jpg",
            "images": [
              "images/LunchBox/TiffinSteellidBlack/Main.jpg",
              "images/LunchBox/TiffinSteellidBlack/Tiffin (Steel lid) Black-2.jpg",
              "images/LunchBox/TiffinSteellidBlack/Tiffin (Steel lid) Black-3.jpg",
              "images/LunchBox/TiffinSteellidBlack/Tiffin (Steel lid) Black-4.jpg"
            ]
          },
          {
            "id": "tiffin-steel-lid-blue",
            "name": "Tiffin Steel Lid Blue",
            "image": "images/LunchBox/TiffinSteellidBlue/Main.jpg",
            "images": [
              "images/LunchBox/TiffinSteellidBlue/Main.jpg",
              "images/LunchBox/TiffinSteellidBlue/Tiffin (Steel lid) Blue-2.jpg",
              "images/LunchBox/TiffinSteellidBlue/Tiffin (Steel lid) Blue-3.jpg",
              "images/LunchBox/TiffinSteellidBlue/Tiffin (Steel lid) Blue-4.jpg"
            ]
          }
        ]
      }
    ]
  }
];
